### ISSUE TITLE
看看这个吧

### ISSUE THREAD

**Issue by sunJ96** [panhainan/DS-Java#2]
这两天公司准备做个论坛，所以想先在网上看看大佬们的东西启蒙下（没做过论坛），在csdn上看了一个项目（时间是19年4月的，标记的原创）觉得还可以，作者把前后端的模块都截图了出来，看起来非常不错的，然鹅木有源码，紧接着又翻了几篇文章，突然在里面又发现一篇一模一样的，且附带了原文链接，点进来就到你这里了，看了下时间最早是14年的。咱也不知道说啥，甩链接你自己看看吧：[链接](https://blog.csdn.net/qq_34417749/article/details/90065984) 作者qq：1097056559

**Comment by AmosHuKe** [comment]
### 盗版嫌疑：
* 转载未标明出处
* 文章放置于原创位置

**Comment by sunJ96** [comment]
刚看到，他的文章来自于 [链接](https://me.csdn.net/llqqxf)这里，尴尬

**Comment by sunJ96** [comment]
后续（QQ聊天记录）：
![1](https://s2.ax1x.com/2019/08/13/m9CgU0.png)
![2](https://s2.ax1x.com/2019/08/13/m9CcEq.png)

**Comment by panhainan** [comment]
感谢这个兄弟，我之前也遇到过，在最代码网站里面，也有人拿我的代码去收费，这次看到你发的，多谢了，我去看看

**Comment by sunJ96** [comment]
大佬还是把开源协议加上吧
